<?php
/**
 * Created by PhpStorm.
 * User: paskuale
 * Date: 27/09/18
 * Time: 9.21
 */

namespace paskuale75\yii2themes\src\components;

use Yii;
use yii\base\Component;
use linslin\yii2\curl;
use yii\helpers\VarDumper;
use yii\helpers\Json;
use yii\base\BootstrapInterface;
use yii\base\Application;

/*
 * inspired by https://github.com/YetOpen/YSkebbySms
 */


class ThemeManager extends Component implements BootstrapInterface
{

    public $selectedTheme;



    public function bootstrap($app)
    {
        $app->on(Application::EVENT_BEFORE_REQUEST, function () {
            // do something here
            $this->selectedTheme = 'sb_cleanblog';//Yii::$app->settings->get('theme', 'general');
            //Yii::setAlias('@theme', realpath(dirname(__FILE__)."/../../themes/$theme"));
            Yii::setAlias('@theme', realpath(dirname(__FILE__)."/../themes/$this->selectedTheme"));
        });
    }


    /**
     * @return mixed
     */
    public function getSelectedTheme()
    {
        return $this->selectedTheme;
    }

    /**
     * @param mixed $selectedTheme
     */
    public function setSelectedTheme($selectedTheme)
    {
        $this->selectedTheme = $selectedTheme;
    }

    /*public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($this->prefix)){
            $this->prefix = $this->geoPrefixs['Italia'];
        }
    }*/




}